# Generated by Django 2.2.6 on 2019-11-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarkupKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markup_key', models.CharField(blank=True, max_length=255, null=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
