# Generated by Django 2.2.6 on 2019-11-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0003_chinapayments_container_pakistanipayment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChinaPayments',
            new_name='ChinaPayment',
        ),
    ]
