# Generated by Django 2.2.6 on 2019-11-10 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0004_auto_20191109_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carton_number', models.CharField(max_length=255)),
                ('carton_name', models.CharField(blank=True, max_length=255, null=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='container.Container')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=255)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('carton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='container.Carton')),
            ],
        ),
    ]
